export type CSSStyle = {
    width?: string|undefined,
    height?: string|undefined,
    borderWidth?: string|undefined,
    borderStyle?: string|undefined,
    borderRadius?: string|undefined,
    fontSize?: string|undefined,
    padding?: string|undefined,
    paddingTop?: string|undefined,
    paddingBottom?: string|undefined,
    paddingLeft?: string|undefined,
    paddingRight?: string|undefined,
    top?: string|undefined,
    bottom?: string|undefined,
    left?: string|undefined,
    right?: string|undefined,    
}